# Generated by Django 2.2.10 on 2020-03-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0006_add_event_remind_sent_at")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        )
    ]
