# Generated by Django 2.2.13 on 2023-10-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("areas", "0006_add_contract_zone_secondary_contact_info")]

    operations = [
        migrations.AlterField(
            model_name="contractzone",
            name="origin_id",
            field=models.CharField(max_length=50, verbose_name="origin ID"),
        )
    ]
