# Generated by Django 4.2.23 on 2025-10-31 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("areas", "0007_make_contract_zone_origin_id_non_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedDate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason for blocking this date",
                        verbose_name="reason",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "contract_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_dates",
                        to="areas.contractzone",
                        verbose_name="contract zone",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "blocked date",
                "verbose_name_plural": "blocked dates",
                "ordering": ("date", "contract_zone"),
                "unique_together": {("date", "contract_zone")},
            },
        ),
    ]
