services:
    postgres:
        image: postgis/postgis:17-3.5-alpine
        restart: on-failure
        environment:
            POSTGRES_USER: haravajarjestelma
            POSTGRES_PASSWORD: haravajarjestelma
            POSTGRES_DB: haravajarjestelma
        ports:
            - 5434:5432
        volumes:
          - pgdata:/var/lib/postgresql/data
        container_name: haravajarjestelma-db

    django:
        build:
            context: .
            target: development
        env_file:
            - compose.env
        environment:
            DATABASE_URL: postgres://haravajarjestelma:haravajarjestelma@haravajarjestelma-db/haravajarjestelma
            DATABASE_HOST: haravajarjestelma-db.helsinki
        volumes:
            - .:/app
        ports:
            - 127.0.0.1:8085:8000
        depends_on:
            - postgres
        container_name: haravajarjestelma-backend

volumes:
    pgdata:
        driver: local

networks:
    default:
        name: helsinki
