name: Build & Production
on:
  push:
    tags:
      - 'release-*'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  production:
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_SECRET_CORS_ORIGIN_ALLOW_ALL: 1
          K8S_SECRET_SECRET_KEY: ${{ secrets.GH_STABLE_DJANGO_SECRET_KEY }}
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_TOKEN_AUTH_AUTHSERVER_URL: "https://api.hel.fi/sso/openid"
          K8S_SECRET_DEFAULT_FROM_EMAIL: 'Puistotalkoot <noreply@mail.hel.ninja>'
          K8S_SECRET_EXCLUDED_CONTRACT_ZONES: ${{ secrets.EXCLUDED_CONTRACT_ZONES }}
          K8S_SECRET_HELSINKI_WFS_BASE_URL: ${{ secrets.GH_PROD_SECRET_HELSINKI_WFS_BASE_URL }}
          K8S_SECRET_MAIL_MAILGUN_API: 'https://api.eu.mailgun.net/v3'
          K8S_SECRET_MAIL_MAILGUN_DOMAIN: 'mail.hel.ninja'
          K8S_SECRET_MAIL_MAILGUN_KEY: ${{ secrets.GH_PROD_SECRET_MAIL_MAILGUN_KEY }}
          K8S_SECRET_MAILER_EMAIL_BACKEND: 'anymail.backends.mailgun.EmailBackend'
          K8S_SECRET_SENTRY_DSN: ${{ secrets.GH_PROD_SENTRY_DSN }}
          K8S_SECRET_SENTRY_ENVIRONMENT: 'production'



